# Generated by Django 3.2.8 on 2021-10-19 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('subject', models.TextField(blank=True)),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='time')),
                ('last_updated', models.DateTimeField(verbose_name='last_updated')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='time')),
                ('comment', models.TextField()),
                ('name', models.TextField(blank=True)),
                ('thread', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='board.thread')),
            ],
            options={
                'ordering': ['time'],
            },
        ),
    ]
