# Generated by Django 3.2.8 on 2021-10-27 07:06

import board.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to=board.models.Post.rename),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
